terraform {
  required_version = ">= 1.0.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  backend "azurerm" {
    resource_group_name  = "prodessy"
    # REPLACE THIS with the storage account name generated by setup_backend.sh
    storage_account_name = "tfstateprod178967"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}

# Use the existing resource group 'prodessy'
data "azurerm_resource_group" "rg" {
  name = "prodessy"
}

resource "azurerm_storage_account" "web" {
  # Storage account names must be unique, lowercase, alphanumeric, 3-24 chars.
  name                     = "assetpilotwebadmin123"
  resource_group_name      = data.azurerm_resource_group.rg.name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"

  static_website {
    index_document     = "index.html"
    error_404_document = "index.html" # Important for Flutter web routing
  }
}
